layout: [
  [BT_CLR,    XXXXX,    XXXXX],
  [XXXXXX,    XXXXX,    XXXXX],
  [XXXXXX,    XXXXX,    XXXXX],
  [XXXXXX,    XXXXX,    XXXXX],
  [XXXXXX,    XXXXX,    XXXXX],
  [XXXXXX,    XXXXX,    XXXXX],
  [XXXXXX,    XXXXX,    XXXXX],
  [XXXXXX,    XXXXX,    XXXXX],
  [BT,        XXXXX,    XXXXX]
]